In [1]:

import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

print 'Done!'


Done!


In [13]:

sess = tf.InteractiveSession()

a = tf.constant(np.random.randn(2,6,5,1))
length = 5

splits = tf.split(a, [1 for i in xrange(length)], 2)

for i in splits:
    print i

sess.close()


Tensor("split_9:0", shape=(2, 6, 1, 1), dtype=float64)
Tensor("split_9:1", shape=(2, 6, 1, 1), dtype=float64)
Tensor("split_9:2", shape=(2, 6, 1, 1), dtype=float64)
Tensor("split_9:3", shape=(2, 6, 1, 1), dtype=float64)
Tensor("split_9:4", shape=(2, 6, 1, 1), dtype=float64)


In [49]:
a = np.reshape(np.array([1,3,5,6,8],dtype=np.float32),(5,1,1))
print a
print (a - min(a))/(max(a) - min(a))

[[[ 1.]]

 [[ 3.]]

 [[ 5.]]

 [[ 6.]]

 [[ 8.]]]
[[[ 0.        ]]

 [[ 0.2857143 ]]

 [[ 0.5714286 ]]

 [[ 0.71428573]]

 [[ 1.        ]]]


In [9]:
a = np.random.rand(4,6)
print a
b = np.reshape(a,(12,2))
c = np.reshape(b,(4,6))
print c
print np.isequal(a,c)

[[ 0.50188795  0.08100909  0.94731041  0.12375532  0.74145957  0.29483983]
 [ 0.92122069  0.34886031  0.13710467  0.42138533  0.11019109  0.56633362]
 [ 0.47789694  0.15282057  0.73730196  0.70721533  0.60273081  0.17888847]
 [ 0.56173151  0.15581723  0.09425084  0.53515419  0.42889372  0.61140256]]
[[ 0.50188795  0.08100909  0.94731041  0.12375532  0.74145957  0.29483983]
 [ 0.92122069  0.34886031  0.13710467  0.42138533  0.11019109  0.56633362]
 [ 0.47789694  0.15282057  0.73730196  0.70721533  0.60273081  0.17888847]
 [ 0.56173151  0.15581723  0.09425084  0.53515419  0.42889372  0.61140256]]


AttributeError: 'module' object has no attribute 'isequal'

In [13]:
a,b = np.random.rand(2,3),np.random.rand(2,3)
print np.concatenate((a,b))
print np.concatenate((a,[]))


[[ 0.58174379  0.68289626  0.59692552]
 [ 0.12199691  0.24861072  0.71586249]
 [ 0.74742146  0.88357217  0.57861628]
 [ 0.10501667  0.1923477   0.41892348]]


ValueError: all the input arrays must have same number of dimensions