In [1]:

import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

print 'Done!'


Done!


In [6]:



class MyClass:
    def __init__(self):
        self.a = 1
        self.b = 2
    def run(self,params):
        for key, value in params.items():
            setattr(self, key, value)
        print self.a
        
c = MyClass()
c.run({'a':3})


3


In [15]:
ns = [float(i) for i in xrange(1,11)]
f = 0.66

ratio = [(((1 - f**n)*0.5) + ((f**n)*(2**n)*0.5))**(1/n) for n in ns]

for n,r in zip(ns,ratio):
    print '{}:{}'.format(n,r)

1.0:0.83
2.0:1.07396461767
3.0:1.14629836889
4.0:1.17760803577
5.0:1.19541214938
6.0:1.20775156931
7.0:1.21744145832
8.0:1.22559010033
9.0:1.23268076514
10.0:1.23895169128


In [9]:
a = np.random.rand(4,6)
print a
b = np.reshape(a,(12,2))
c = np.reshape(b,(4,6))
print c
print np.isequal(a,c)

[[ 0.50188795  0.08100909  0.94731041  0.12375532  0.74145957  0.29483983]
 [ 0.92122069  0.34886031  0.13710467  0.42138533  0.11019109  0.56633362]
 [ 0.47789694  0.15282057  0.73730196  0.70721533  0.60273081  0.17888847]
 [ 0.56173151  0.15581723  0.09425084  0.53515419  0.42889372  0.61140256]]
[[ 0.50188795  0.08100909  0.94731041  0.12375532  0.74145957  0.29483983]
 [ 0.92122069  0.34886031  0.13710467  0.42138533  0.11019109  0.56633362]
 [ 0.47789694  0.15282057  0.73730196  0.70721533  0.60273081  0.17888847]
 [ 0.56173151  0.15581723  0.09425084  0.53515419  0.42889372  0.61140256]]


AttributeError: 'module' object has no attribute 'isequal'

In [13]:
a,b = np.random.rand(2,3),np.random.rand(2,3)
print np.concatenate((a,b))
print np.concatenate((a,[]))


[[ 0.58174379  0.68289626  0.59692552]
 [ 0.12199691  0.24861072  0.71586249]
 [ 0.74742146  0.88357217  0.57861628]
 [ 0.10501667  0.1923477   0.41892348]]


ValueError: all the input arrays must have same number of dimensions